/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class CreateRetrieveUpdateEmployee extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement stat;
    private String host = "jdbc:derby://localhost:1527/FastestDeliveryman";
    private String user = "nbuser";
    private String password = "nbuser";
    private String tableName = "DELIVERYMAN";
    
    public CreateRetrieveUpdateEmployee() {
        initComponents();
        setTitle("Create, Retrieve and Update Employee");
        setSize(580,480);
        setIcon();
        setLocationRelativeTo(null);
        createConnection();
    }
    
     private void createConnection() {
        try{
            conn = DriverManager.getConnection(host, user, password);
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionGroup = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfEmpID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfEmpName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfEmpPassword = new javax.swing.JTextField();
        jtfEmpEmail = new javax.swing.JTextField();
        jtfEmpContact = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jbtCreate = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEmpAddress = new javax.swing.JTextArea();
        jrbStaff = new javax.swing.JRadioButton();
        jrbManager = new javax.swing.JRadioButton();
        jbtBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtClearText = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background blur.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background blur.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Employee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 43, 78, 26);

        jtfEmpID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtfEmpID);
        jtfEmpID.setBounds(252, 44, 92, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Employee Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 81, 122, 26);

        jtfEmpName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtfEmpName);
        jtfEmpName.setBounds(252, 120, 92, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contact Number (eg. 013-7584953)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 157, 224, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 119, 99, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 199, 83, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 256, 48, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Postion");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 360, 45, 23);

        jtfEmpPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtfEmpPassword);
        jtfEmpPassword.setBounds(252, 82, 128, 26);

        jtfEmpEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtfEmpEmail);
        jtfEmpEmail.setBounds(252, 195, 166, 26);

        jtfEmpContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtfEmpContact);
        jtfEmpContact.setBounds(252, 158, 128, 26);

        jbtSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtSearch);
        jbtSearch.setBounds(350, 390, 103, 40);

        jbtCreate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Create.png"))); // NOI18N
        jbtCreate.setText("Create");
        jbtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCreate);
        jbtCreate.setBounds(240, 390, 103, 40);

        jbtUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Update.png"))); // NOI18N
        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtUpdate);
        jbtUpdate.setBounds(460, 390, 107, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Employee Profile");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 570, 32);

        jtaEmpAddress.setColumns(20);
        jtaEmpAddress.setRows(5);
        jScrollPane1.setViewportView(jtaEmpAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(252, 232, 166, 96);

        positionGroup.add(jrbStaff);
        jrbStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbStaff.setText("Staff");
        getContentPane().add(jrbStaff);
        jrbStaff.setBounds(252, 359, 53, 25);

        positionGroup.add(jrbManager);
        jrbManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbManager.setText("Manager");
        getContentPane().add(jrbManager);
        jrbManager.setBounds(323, 359, 77, 25);

        jbtBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back .png"))); // NOI18N
        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtBack);
        jbtBack.setBounds(0, 390, 90, 40);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 400, 73, 23);

        jbtClearText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtClearText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ClearText.png"))); // NOI18N
        jbtClearText.setText("Clear Text");
        getContentPane().add(jbtClearText);
        jbtClearText.setBounds(100, 390, 130, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background blur.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 4, 570, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateActionPerformed
        String empID = jtfEmpID.getText();
            ResultSet rs = selectRecord(empID);
            String position;
            
            try{
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "This employee ID already exists.", "DUPLICATE RECORD", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    String insertStr = "INSERT INTO " + tableName + " VALUES(?,?,?,?,?,?,?)";
                    stat = conn.prepareStatement(insertStr);
                    stat.setString(1, empID);
                    stat.setString(2, jtfEmpPassword.getText());
                    stat.setString(3, jtfEmpName.getText());
                    stat.setString(4, jtfEmpContact.getText());
                    stat.setString(5, jtfEmpEmail.getText());
                    stat.setString(6, jtaEmpAddress.getText());
                    if(jrbStaff.isSelected()){
                        position = "staff";
                        stat.setString(7, position);
                    }
                    else if(jrbManager.isSelected()){
                        position = "manager";
                        stat.setString(7, position);
                    }
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "New employee '"+ empID + "' is add", "Successfully add", JOptionPane.INFORMATION_MESSAGE);
                    clearText();
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbtCreateActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        String empID = jtfEmpID.getText();
        ResultSet rs = selectRecord(empID);
        try{ 
            if (rs.next()) {
                jtfEmpPassword.setText(rs.getString("employeepassword"));
                jtfEmpName.setText(rs.getString("employeename"));
                jtfEmpContact.setText(rs.getString("employeecontactno"));
                jtfEmpEmail.setText(rs.getString("employeeemail"));
                jtaEmpAddress.setText(rs.getString("employeeaddress"));
                String position = rs.getString("employeepostition");
                if(position.equals("staff")){
                    jrbStaff.setSelected(true);
                    jrbManager.setSelected(false);
                }
                else{
                    jrbStaff.setSelected(false);
                    jrbManager.setSelected(true);
                }
            } else
                JOptionPane.showMessageDialog(null, "No such employee id.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        String empID = jtfEmpID.getText();
        ResultSet rs = selectRecord(empID);
            try{
                if(rs.next()){
                    String password = jtfEmpPassword.getText();
                    String empname = jtfEmpName.getText();
                    String contactno = jtfEmpContact.getText();
                    String email = jtfEmpEmail.getText();
                    String address = jtaEmpAddress.getText();
                    String position = null;
                    if(jrbStaff.isSelected()){
                        position = "staff";
                    }
                    else if(jrbManager.isSelected()){
                        position = "manager";
                    }
                    String updateStr = "Update " + tableName + " eSET employeepassword = ?, employeename = ?, "
                            + "employeecontactno = ?, employeeemail = ?, employeeaddress = ?, employeepostition = ? WHERE employeeid = ?";
                    stat = conn.prepareStatement(updateStr);
                    stat.setString(1, password);
                    stat.setString(2, empname);
                    stat.setString(3, contactno);
                    stat.setString(4, email);
                    stat.setString(5, address);
                    stat.setString(6, position);
                    stat.setString(7, empID);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Employee ID '"+ empID + "' is updated", "Successfully update", JOptionPane.INFORMATION_MESSAGE);
                    clearText();
                }
                else{
                    JOptionPane.showMessageDialog(null,"No such programme code", "Record not found", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRetrieveUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRetrieveUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRetrieveUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRetrieveUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateRetrieveUpdateEmployee cruEmployee = new CreateRetrieveUpdateEmployee();
                cruEmployee.setVisible(true);
                cruEmployee.setResizable(false);
            }
        });
    }
    
    public ResultSet selectRecord(String empID) {
        String queryStr = "SELECT * FROM " + tableName + " WHERE employeeid = ?";
        ResultSet rs = null;
        try { 
            stat = conn.prepareStatement(queryStr);
            stat.setString(1, empID);
            rs = stat.executeQuery();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return rs;
    }
    
    private void clearText(){
        jtfEmpID.setText(" ");
        jtfEmpName.setText(" ");
        jtfEmpPassword.setText(" ");
        jtfEmpContact.setText(" ");
        jtfEmpEmail.setText(" ");
        jtaEmpAddress.setText(" ");
        positionGroup.setSelected(null, rootPaneCheckingEnabled);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtClearText;
    private javax.swing.JButton jbtCreate;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JRadioButton jrbManager;
    private javax.swing.JRadioButton jrbStaff;
    private javax.swing.JTextArea jtaEmpAddress;
    private javax.swing.JTextField jtfEmpContact;
    private javax.swing.JTextField jtfEmpEmail;
    private javax.swing.JTextField jtfEmpID;
    private javax.swing.JTextField jtfEmpName;
    private javax.swing.JTextField jtfEmpPassword;
    private javax.swing.ButtonGroup positionGroup;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Mamamiazza.gif")));
    }
}
